import Head from 'next/head'
import Image from 'next/image'
import BlogSection from '../components/BlogSection'
import { getAllPostagems} from '../lib/dato-cms'
import styles from '../styles/Home.module.css'

export default function Home({postagens}) {
  console.log(postagens)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CARVALHAÇO
        </h1>
      </main>
      
          <BlogSection postagens={postagens} />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const postagens = await getAllPostagems();

  return {
    props: {
      postagens,
    },
    revalidate: 120,
  };
};